"""initial schema

Revision ID: c703c2a51d03
Revises: 
Create Date: 2026-07-26 23:42:45.574846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c703c2a51d03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='formstatus'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('form_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('short_text', 'long_text', 'multiple_choice', 'dropdown', 'email', 'number', 'yes_no', 'rating', name='questiontype'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_form_id'), 'questions', ['form_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('form_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_form_id'), 'responses', ['form_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('response_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_response_id'), 'answers', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_response_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_responses_form_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_questions_form_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
